version: "2"

services:

  mariadb:
    image: mariadb
    ports:
     - "3306:3306"
    environment:
      MYSQL_DATABASE: appCs
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - mariadb

  maildev:
    image: djfarrelly/maildev
    ports:
      - '1080:80'